version: '3.7'
services:

  api:
    build:
      context: ./rpctest
      dockerfile: docker/docker_files/Dockerfile
    restart: unless-stopped
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./rpctest:/code
    ports:
      - 8000:8000